updated mymanim script

diff --git a/mymanim b/mymanim
--- a/mymanim
+++ b/mymanim
@@ -1,7 +1,24 @@
 #!/usr/bin/bash
+
+MANIM_RES_DIR="$HOME/Films/manim"
+PODMAN_IMG_NAME="manim-img"
+
+[ -e "$MANIM_RES_DIR" ] || {
+    echo >&2 "[Info]  Creating default manim dir: $MANIM_RES_DIR"
+    mkdir -p "$MANIM_RES_DIR"
+}
+
+podman images --noheading --format "{{ .Repository }}" "$PODMAN_IMG_NAME" | grep -q "/manim-img$"
+[ $? -ne 0 ] && {
+  echo >&2 "[Error] The $MANIM_RES_DIR podman image doesn't exist yet."
+  echo >&2 "        Build it manually from the git repository."
+  exit 1
+}
+
+echo >&2 "[Info]  Starting the manim..."
 podman run -ti --rm --name mymanim \
-    -v "/home/pstodulk/Films/manim:/output:Z" \
+    -v "$MANIM_RES_DIR:/output:Z" \
     -v "$PWD:/input:ro,Z" \
     -w "/input" \
-    manim-img $@
+    "$PODMAN_IMG_NAME" $@
 
